### ISSUE TITLE
Test should return page 0

### ISSUE THREAD

**Issue by agory** [PolytechLyon/cloud-project-equipe-1#11]
Bonjour @Slashgear,

Depuis que j'ai activé le cache, il m'arrive parfois mais rarement de rater le test suivant : 
```js
it('should return page 0', done => {
        let usersFirstPage0;
        request.get('/user').end((err, res) => {
            usersFirstPage0 = _.map(res.body, user => _.omit(user, 'id'));
        });
        request.get('/user?page=0').end((err, res) => {
            expect(usersFirstPage0).toEqual(_.map(res.body, user => _.omit(user, 'id')))
            done();
        });
});
```
Puisque les 2 requêtes sont lancés simultanément, est-il possible que le callback de la deuxième request soit lancé en premier. Cela pourrait expliquer pourquoi  j'obtiens undefined sur usersFirstPage0 dans le expect. 

De plus, lorsque j'ai modifié localement votre test comme cela : 
```js
it('should return page 0', done => {
        let usersFirstPage0;
        request.get('/user').end((err, res) => {
            usersFirstPage0 = _.map(res.body, user => _.omit(user, 'id'));
            request.get('/user?page=0').end((err, res) => {
                expect(usersFirstPage0).toEqual(_.map(res.body, user => _.omit(user, 'id')))
                done();
            });
        });
});
```
Je n'ai plus eu le problème.

Merci de votre attention.

**Comment by Slashgear** [comment]
Ok on va partir sur ça :) je fais une nouvelle release. Je te laisserai mettre un message.

**Comment by Slashgear** [comment]
Quand l'issue est clair, qu'en plus il y a un correctif, je ne vois pas pourquoi je ne l'appliquerai pas. 
Vive les cours open source!

**Comment by agory** [comment]
Merci de votre retour
